Feature/create order
Swat-FaztOrder/Backend pull request #45
Opened 2020-11-28 02:40 UTC by jlazo

This PR includes:

- The order entity
- The order service
- The order repository
- The order controller which includes get all order and create order

2020-11-30 16:01 UTC, jcmexdev requested changes
Como estábamos tardando mucho en hacer los reviews estamos mezclando cambios distintos en un mismo PR esto no debería pasar ya que dificulta la revisión de un solo feature, nos comprometimos a revisar tan pronto estén lo PR para que esto no tenga que repetirse en el futuro 😎.

2020-11-30 16:01 UTC, jcmexdev commented on src/modules/order/dtos/order-filter.dto.ts
> +export class OrderFilterDto {}
it's empty, it'll be implemented later right?

2020-11-30 16:01 UTC, jcmexdev commented on src/modules/order/order.entity.ts
> +  @Column({ name: 'waitress_id', type: 'int', nullable: true })
why the waitress is nullable?

2020-11-30 16:01 UTC, jcmexdev commented on src/modules/order/order.entity.ts
> +    default: OrderStatus.PROGRESS,
The status that you use in this enum isn't the same in the database schema, we should discuss that.

2020-11-30 16:01 UTC, jcmexdev commented on src/modules/order/order.entity.ts
> +  authorId: number;
can we use waitressId and delete this element? or what is the difference, because waitress is who create the order right?

2020-11-30 16:01 UTC, jcmexdev commented on src/modules/order/order.service.ts
> +    return this._orderRepository.find();
you're returning the query directly, you have to use OrderResponseDto so please change it.

2020-11-30 16:01 UTC, jcmexdev commented on src/modules/order/order.service.ts
> +    // Cancelación de ordenes con motivo?
I think that we should use a logical delete to have the control of all orders and add a field to describe the cancellation reason. or what do you think about that?

2020-11-30 16:01 UTC, jcmexdev commented on src/modules/order/order.status.enum.ts
> +export enum OrderStatus {
we should use the status on database schema

2020-11-30 16:01 UTC, jcmexdev commented on src/modules/user/user.service.ts
> +    if (user) throw new NotFoundException('user_not_found');
You forgot the user negation **!user** to get a good exception trigger, if you do this a existing user always be **not found**

2020-11-30 16:01 UTC, jcmexdev commented on src/modules/user/user.service.ts
> +    return user.save();
you're returning a query execute,  you have to return a UserResponseDto currently this method returns all the user data including the password. 🚨

2020-11-30 16:01 UTC, jcmexdev commented on src/modules/user/user.service.ts
> +    if (user) throw new NotFoundException('user_not_found');
the same of !user conditional

2020-12-01 00:21 UTC, jlazo commented on src/modules/order/dtos/order-filter.dto.ts
> +export class OrderFilterDto {}
It is correct

2020-12-01 00:21 UTC, jlazo commented on src/modules/order/order.entity.ts
> +  @Column({ name: 'waitress_id', type: 'int', nullable: true })
:'( Because you can order by phone, lol, It must be false

2020-12-01 00:27 UTC, jlazo commented on src/modules/order/order.entity.ts
> +    default: OrderStatus.PROGRESS,
Because, only put the initial status not the rest

2020-12-01 00:28 UTC, jlazo commented on src/modules/order/order.entity.ts
> +  authorId: number;
Maybe, someone create the order because the waitress dont arrive yet hahahaha

2020-12-01 00:31 UTC, jlazo commented on src/modules/order/order.service.ts
> +    return this._orderRepository.find();
You are right!

2020-12-01 00:33 UTC, jlazo commented on src/modules/order/order.service.ts
> +    // Cancelación de ordenes con motivo?
This must be a new issue. The cancelation with reason is the correct way

2020-12-01 00:34 UTC, jlazo commented on src/modules/order/order.status.enum.ts
> +export enum OrderStatus {
OrderStatus is enum in database

2020-12-01 00:34 UTC, jlazo commented on src/modules/user/user.service.ts
> +    if (user) throw new NotFoundException('user_not_found');
Holy s.....!

2020-12-01 13:54 UTC, jcmexdev requested changes
you are very near to merge we only need some changes before do that

2020-12-01 13:54 UTC, jcmexdev commented on src/modules/user/user.controller.ts
> +    console.log
upss! something wrong happen here, it has to be removed.

2020-12-01 13:54 UTC, jcmexdev commented on src/modules/order/order.entity.ts
> +    default: OrderStatus.PROGRESS,
can you set the initial status as taking ?

2020-12-01 13:54 UTC, jcmexdev commented on src/modules/order/order.entity.ts
> +  authorId: number;
can you remove this field please

2020-12-01 13:54 UTC, jcmexdev commented on src/modules/order/order.status.enum.ts
> +export enum OrderStatus {
so we agreed the following status taking, waiting, preparing and ready, can you add this please and it will be completed.

2020-12-01 23:16 UTC, jcmexdev commented on src/modules/order/dtos/order-create.dto.ts
> -  @ApiProperty({
why you remove this properties?

2020-12-01 23:19 UTC, jlazo commented on src/modules/order/dtos/order-create.dto.ts
> -  @ApiProperty({
Because I get the user_id from JWT

2020-12-01 23:21 UTC, jcmexdev requested changes
Solo falta quitar el authorId de OrderCreateDto

2020-12-01 23:25 UTC, jlazo commented
> Solo falta quitar el authorId de OrderCreateDto

Si lo quito no tengo forma de hacerle llegar el valor al order.service.ts

2020-12-01 23:30 UTC, jcmexdev approved these changes

2020-12-01 23:31 UTC, merged