Fix/dish creation
Swat-FaztOrder/Backend pull request #64
Opened 2020-12-04 05:14 UTC by AlanDavd

Fix creation of dish with an unavailable category Id

- Import MenuCategory into MenuDishesService
- Validate that the category id already exists to create a dish

2020-12-04 15:24 UTC, jcmexdev requested changes

2020-12-04 15:24 UTC, jcmexdev commented on src/modules/menu-category/menu-category.module.ts
> +  exports: [MenuCategoryService],
why you exports this service?, you can add it in the menu-dishes module like the other modules under typeorm.forFeature function for example:
imports: [
    TypeOrmModule.forFeature([
      OrderDetailRepository,
      OrderRepository,
      UserRepository,
      MenuDishesRepository,
    ]),
  ],

2020-12-04 15:24 UTC, jcmexdev commented on src/modules/menu-dishes/menu-dishes.module.ts
> +    TypeOrmModule.forFeature([MenuDishesRepository]),
you can add the menu category repository here and you don't need the export in menu category module:
TypeOrmModule.forFeature([MenuDishesRepository, MenuCategorRepository ]),

2020-12-04 15:24 UTC, jcmexdev commented on src/modules/menu-dishes/menu-dishes.service.ts
> +    private readonly _menuCategoriesService: MenuCategoryService,
here we should use the repositories like the other models instead use service directly to have a same conventions

2020-12-04 20:58 UTC, jcmexdev approved these changes
Good Job!!

2020-12-05 02:24 UTC, jlazo approved these changes

2020-12-05 02:24 UTC, merged